apiVersion: v1
kind: Service
metadata:
  name: can-you-hear-it-service
  namespace: default
spec:
  selector:
    app: can-you-hear-it-pods
  type: NodePort
  ports:
    - port: 80
      targetPort: 8501
      nodePort: 30001
